### ISSUE TITLE
This node uses help

### ISSUE THREAD

**Issue by ZHonry** [inwaar/node-red-contrib-gree-hvac#1]
I use the HomeAssistant-GreeClimateComponent plug-in in ha, which can access my GREE AC normally, but using your node in NR, the connection is always displayed, can you please see what the problem is? (My English is not good, this is translated by Google, please forgive me!)
![image](https://user-images.githubusercontent.com/22869840/75472657-cca93e00-59ce-11ea-90fa-53fd452e8e93.png)
![image](https://user-images.githubusercontent.com/22869840/75472694-d92d9680-59ce-11ea-9e19-7b9c4fc59dda.png)
No other tips.
I look forward to your answer, thank you.

**Comment by inwaar** [comment]
Hi, ZHonry.
"Connecting..." usually means that the node can not connect to AC, the things you could check:

1. provide correct IP address of the AC (try making it static in your router)
2. the node can't connect to AC because of network config (try to ping AC ip-address from your NodeRED device)

**Comment by ZHonry** [comment]
I installed nodered in docker, and the Ping result is as shown in the figure. When using another project transferred to mqtt, it was registered successfully and cannot be bound. Is it because the air conditioner is the new model?
![image](https://user-images.githubusercontent.com/22869840/79263061-d296a800-7ec4-11ea-8a03-ca98fb757cb3.png)
![image](https://user-images.githubusercontent.com/22869840/79263071-d4f90200-7ec4-11ea-9781-7afb8892f74f.png)

**Comment by inwaar** [comment]
Could you try temporarily running NodeRED with the gree-node outside of the docker to see if the problems is not related to docker?

**Comment by ZHonry** [comment]
After installing nodered in Debian, it has been confirmed that the air conditioner can be pinged, but it is still the same as installing nodered in docker. The air conditioner currently uses UDP distribution network and is not bound in the app.
There is really no coding foundation at all, please forgive me.
<img width="1092" alt="iShot2020-04-15下午10 35 30" src="https://user-images.githubusercontent.com/22869840/79355092-d3384880-7f6f-11ea-98f9-7026249b0029.png">
<img width="544" alt="iShot2020-04-15下午10 35 39" src="https://user-images.githubusercontent.com/22869840/79355109-daf7ed00-7f6f-11ea-8271-1589cdcb14e2.png">
<img width="419" alt="iShot2020-04-15下午10 36 20" src="https://user-images.githubusercontent.com/22869840/79355120-dc291a00-7f6f-11ea-83c3-6b31e377932c.png">

**Comment by inwaar** [comment]
I've released a new version 0.1.1 where you can turn on debug messages: 
![image](https://user-images.githubusercontent.com/3331076/79378602-476dee80-7f66-11ea-9bdf-25bc321dc366.png)

The version will be available in NodeRED palette in a short while.
Would be nice to see what you have in the logs of you NodeRED process.

**Comment by ZHonry** [comment]
This is the log file
[greeac.log](https://github.com/inwaar/node-red-contrib-gree-hvac/files/4484969/greeac.log)

**Comment by inwaar** [comment]
Try the version 0.1.2 of this node.

**Comment by ZHonry** [comment]
[greeacv0.1.2.log](https://github.com/inwaar/node-red-contrib-gree-hvac/files/4485938/greeacv0.1.2.log)
Log file for 0.1.2

**Comment by inwaar** [comment]
Try 0.1.3

**Comment by ZHonry** [comment]
I've successfully connected. I'll see if I can control it. Thank you very much for your support.

**Comment by ZHonry** [comment]
Successfully control AC, and can get status, thanks again.
