### ISSUE TITLE
Control setting

### ISSUE THREAD

**Issue by wojtulab** [inwaar/node-red-contrib-gree-hvac#6]
Hello,
is this module allow only read or read/write?
I was wondering how can I set for example heating 23 *C or sth else?

**Comment by inwaar** [comment]
Hi wojtulab, you need to create an `Inject` node with a JSON payload, e.g.:
![image](https://user-images.githubusercontent.com/3331076/140298627-ed4599f7-6d19-45ff-9d7b-7515480a1f6e.png)

The available properties can be seen from the output of the node or over here:
https://github.com/inwaar/gree-hvac-client#properties

**Comment by wojtulab** [comment]
Great, will test it. Thank you!
